[proxies]
data = [
    "http://6fppoz3byx:09e1m7kowx@premium2.travchisproxies.com:12321/session-U0TI8gSX_streaming-1",
    "",
    "",
    "",
    ""
]

[data]
auth = [
    { Email = "", Password = "" },
    { Email = "", Password = "" },
    { Email = "", Password = "" },
    { Email = "", Password = "" },
    { Email = "", Password = "" }
]
